// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: bingbong/bingbong.proto

package golang_grpc_trace_demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BingBongClient is the client API for BingBong service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BingBongClient interface {
	GetBong(ctx context.Context, in *Bing, opts ...grpc.CallOption) (*Bong, error)
}

type bingBongClient struct {
	cc grpc.ClientConnInterface
}

func NewBingBongClient(cc grpc.ClientConnInterface) BingBongClient {
	return &bingBongClient{cc}
}

func (c *bingBongClient) GetBong(ctx context.Context, in *Bing, opts ...grpc.CallOption) (*Bong, error) {
	out := new(Bong)
	err := c.cc.Invoke(ctx, "/BingBong/GetBong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BingBongServer is the server API for BingBong service.
// All implementations must embed UnimplementedBingBongServer
// for forward compatibility
type BingBongServer interface {
	GetBong(context.Context, *Bing) (*Bong, error)
	mustEmbedUnimplementedBingBongServer()
}

// UnimplementedBingBongServer must be embedded to have forward compatible implementations.
type UnimplementedBingBongServer struct {
}

func (UnimplementedBingBongServer) GetBong(context.Context, *Bing) (*Bong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBong not implemented")
}
func (UnimplementedBingBongServer) mustEmbedUnimplementedBingBongServer() {}

// UnsafeBingBongServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BingBongServer will
// result in compilation errors.
type UnsafeBingBongServer interface {
	mustEmbedUnimplementedBingBongServer()
}

func RegisterBingBongServer(s grpc.ServiceRegistrar, srv BingBongServer) {
	s.RegisterService(&BingBong_ServiceDesc, srv)
}

func _BingBong_GetBong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BingBongServer).GetBong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BingBong/GetBong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BingBongServer).GetBong(ctx, req.(*Bing))
	}
	return interceptor(ctx, in, info, handler)
}

// BingBong_ServiceDesc is the grpc.ServiceDesc for BingBong service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BingBong_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BingBong",
	HandlerType: (*BingBongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBong",
			Handler:    _BingBong_GetBong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bingbong/bingbong.proto",
}
