// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: bingbong/bingbong.proto

package golang_grpc_trace_demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bing string `protobuf:"bytes,1,opt,name=bing,proto3" json:"bing,omitempty"`
}

func (x *Bing) Reset() {
	*x = Bing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bingbong_bingbong_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bing) ProtoMessage() {}

func (x *Bing) ProtoReflect() protoreflect.Message {
	mi := &file_bingbong_bingbong_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bing.ProtoReflect.Descriptor instead.
func (*Bing) Descriptor() ([]byte, []int) {
	return file_bingbong_bingbong_proto_rawDescGZIP(), []int{0}
}

func (x *Bing) GetBing() string {
	if x != nil {
		return x.Bing
	}
	return ""
}

type Bong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bong string `protobuf:"bytes,1,opt,name=bong,proto3" json:"bong,omitempty"`
}

func (x *Bong) Reset() {
	*x = Bong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bingbong_bingbong_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bong) ProtoMessage() {}

func (x *Bong) ProtoReflect() protoreflect.Message {
	mi := &file_bingbong_bingbong_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bong.ProtoReflect.Descriptor instead.
func (*Bong) Descriptor() ([]byte, []int) {
	return file_bingbong_bingbong_proto_rawDescGZIP(), []int{1}
}

func (x *Bong) GetBong() string {
	if x != nil {
		return x.Bong
	}
	return ""
}

var File_bingbong_bingbong_proto protoreflect.FileDescriptor

var file_bingbong_bingbong_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x69, 0x6e, 0x67, 0x62, 0x6f, 0x6e, 0x67, 0x2f, 0x62, 0x69, 0x6e, 0x67, 0x62,
	0x6f, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x04, 0x42, 0x69, 0x6e,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x69, 0x6e, 0x67, 0x22, 0x1a, 0x0a, 0x04, 0x42, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x6e,
	0x67, 0x32, 0x25, 0x0a, 0x08, 0x42, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x6e, 0x67, 0x12, 0x19, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6e, 0x67, 0x12, 0x05, 0x2e, 0x42, 0x69, 0x6e, 0x67, 0x1a,
	0x05, 0x2e, 0x42, 0x6f, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x65, 0x6d, 0x61, 0x64, 0x6e, 0x65,
	0x73, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bingbong_bingbong_proto_rawDescOnce sync.Once
	file_bingbong_bingbong_proto_rawDescData = file_bingbong_bingbong_proto_rawDesc
)

func file_bingbong_bingbong_proto_rawDescGZIP() []byte {
	file_bingbong_bingbong_proto_rawDescOnce.Do(func() {
		file_bingbong_bingbong_proto_rawDescData = protoimpl.X.CompressGZIP(file_bingbong_bingbong_proto_rawDescData)
	})
	return file_bingbong_bingbong_proto_rawDescData
}

var file_bingbong_bingbong_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bingbong_bingbong_proto_goTypes = []interface{}{
	(*Bing)(nil), // 0: Bing
	(*Bong)(nil), // 1: Bong
}
var file_bingbong_bingbong_proto_depIdxs = []int32{
	0, // 0: BingBong.GetBong:input_type -> Bing
	1, // 1: BingBong.GetBong:output_type -> Bong
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bingbong_bingbong_proto_init() }
func file_bingbong_bingbong_proto_init() {
	if File_bingbong_bingbong_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bingbong_bingbong_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bingbong_bingbong_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bingbong_bingbong_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bingbong_bingbong_proto_goTypes,
		DependencyIndexes: file_bingbong_bingbong_proto_depIdxs,
		MessageInfos:      file_bingbong_bingbong_proto_msgTypes,
	}.Build()
	File_bingbong_bingbong_proto = out.File
	file_bingbong_bingbong_proto_rawDesc = nil
	file_bingbong_bingbong_proto_goTypes = nil
	file_bingbong_bingbong_proto_depIdxs = nil
}
